import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const { data: session } = useSession();

  if (session) {
    console.log("USER", session.user);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          <li>
            <Link href={"/usuarios"}>usuarios</Link>
          </li>
          <li>
            <Link href={"/usuarios/novo"}>Novo user</Link>
          </li>
          <li></li>
        </ul>
      </div>

      <main className={styles.main}>
        {!session && <button onClick={() => signIn()}>Fazer Login</button>}

        {session && (
          <>
            Olá {session.user?.name}. meu id é {session.user.id}
            <button onClick={() => signOut()}>Sair</button>
          </>
        )}

        <h1 className={styles.title}>Bem vindo a Minha propria página</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
