import Head from "next/head";
import styles from "../styles/Home.module.css";

import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { Banner } from "../components/Banner";
import MenuBotoes from "../components/MenuBotoes";
import { Destaque } from "../components/Destaque";
import { Produtos } from "../components/Produtos";
import { Parceiros } from "../components/parceiros";
import Login2 from "./login2";
import { DestaqueDoDia } from "../components/DestaqueDoDia";

export default function Home() {
  const { data: session } = useSession();

  if (session) {
    console.log("USER", session.user);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <div className={styles.conteudo}>
        {/* <div>
        <ul>
          <li>
            <Link href={"/usuarios"}>usuarios</Link>
          </li>
          <li>
            <Link href={"/usuarios/novo"}>Novo user</Link>
          </li>
        </ul>

        {!session && <button onClick={() => signIn()}>Fazer Login</button>}

        {session && (
          <>
            Olá {session.user.name}. meu id é {session.user.id}
            <button onClick={() => signOut()}>Sair</button>
          </>
        )}
      </div> */}
        <Destaque />

        {/* <div className={styles.titulo}># Destaque do dia</div>
        <DestaqueDoDia /> */}

        <div className={styles.titulo}># VISITE NOSSOS PARCEIROS</div>

        <Parceiros />

        <div className={styles.titulo}># ITENS PROMOCIOANIS</div>
        <Produtos />
      </div>

      <MenuBotoes />
    </div>
  );
}
