import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Banner } from "../components/Banner";
import MenuBotoes from "../components/MenuBotoes";
import { Destaque } from "../components/Destaque";
import { Produtos } from "../components/Produtos";
import { Parceiros } from "../components/parceiros";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>TEC POWER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <div className={styles.conteudo}>
        <Destaque />

        <div className={styles.titulo}># VISITE NOSSOS PARCEIROS</div>

        <Parceiros />

        <div className={styles.titulo}># ITENS PROMOCIOANIS</div>
        <Produtos />
      </div>

      <MenuBotoes />
    </div>
  );
}
